- title: 'Studio Portraits'
  image: '../src/images/studio/studio-1.jpg'
  description: 'Studio portrait session perfect for senior photos, headshots, model photos, and others.'
  link: '/services/studio'
- title: 'Outdoor Portraits'
  image: '../src/images/outdoor/outdoor-1.jpeg'
  description: 'Outdoor portrait session perfect for senior photos, family photos, and more!'
  link: '/services/outdoor'
- title: 'Real Estate'
  image: '../src/images/real-estate/real-estate-1.jpeg'
  description: 'Professional real estate photography with a high ROI'
  link: '/services/real-estate'
